import { test,  chromium, expect } from "@playwright/test"; 
    test.setTimeout(0);
test.only('Salesforce', async({page})=>{ 
await page.goto("https://ford-f1-dev-ed.develop.my.salesforce.com");
await page.waitForTimeout(3000); 
await page.locator(`#username`).fill('sindhujas@testleaf.com');
await page.fill("#password", "MyJob@1993!");
await page.waitForTimeout(3000); 
await page.click("#Login");
console.log(await page.title());
await page.getByRole('button', { name: 'App Launcher' }).click();
console.log(await page.title());
await page.getByText("View All").click(); 
console.log(await page.title());
await page.locator("//div[@data-name='Service']").click();
await page.locator("a[title='Cases'] + * svg").click();
await page.locator("//span[contains(text(),'New Case')]").click();
await page.locator("//input[@placeholder='Search Contacts...']").click();
await page.locator("//span[contains(text(),'New Contact')]").click();
await page.locator("//span[text()='Salutation']/following::a[1]").click();
await page.locator("a[title='Mrs.']").click();
await page.getByPlaceholder("First Name").fill("xyz");
    await page.getByPlaceholder("Last Name").fill("abc");
    await page.locator("//span[contains(text(),'Save')]").click();
    console.log(await page.getByRole("alertdialog").innerText());
    await page.waitForSelector("//input[@placeholder='Search Accounts...']");
    await page.locator("//input[@placeholder='Search Accounts...']").first().click();
    await page.locator("//span[contains(text(),'New Account')]").click();
    await page.locator("//span[contains(text(),'Account Name')]").fill('123');
    await page.locator("//span[text()='Rating']/following::a[1]").click();
    await page.locator("a[title='Hot']").click();
    await page.locator("//span[contains(text(),'Save')]").click();
    await page.waitForTimeout(3000);
    console.log(await page.getByRole("alertdialog").innerText());
    await page.locator("//span[text()='Medium']").first().click();
    await page.locator("//span[text()='High']").last().click();
    await page.locator("//label[text()='Case Origin']//following::button[1]").click();
    await page.locator("//span[text()='Email']").click();
   await page.getByRole('button', { name: 'Save', exact: true }).click();
    console.log(await page.getByRole("alertdialog").innerText());
    await page.locator("//span[text()='Status']//following::span[text()='Edit Status']").click();
    await page.locator("//label[text()='Status']/following::button[1]").first().click();
    await page.locator("//span[text()='Escalated']").click();
    await page.locator("//button[@name='SaveEdit']").click();
    await page.waitForTimeout(3000);
await page.getByTitle('Share an update...').click();
await page.locator("//div[@class ='ql-editor ql-blank slds-rich-text-area__content slds-text-color_weak slds-grow']").fill('updated');
await page.getByTitle('Click, or press Ctrl+Enter').click();
await page.waitForTimeout(4000);
await page.getByRole('link', { name: 'Actions for this Feed Item ' }).first().click();
await page.locator("//span[text()='Like on Chatter']").click();
await page.getByRole("alertdialog").innerText();
console.log(await page.getByRole("alertdialog").innerText());
await page.locator("//span[text()='Chatter']").click();
const verifylikedpost = page.locator(".cuf-feedElement cuf-feedItem").filter({hasText:"Liked"});
await expect(verifylikedpost).toBeVisible;
})  

